title: OS2 FleetOptimiser brugervejledning
description: En step-by-step guide der beskriver brugen af FleetOptimiser
theme: just-the-docs

url: https://just-the-docs.github.io

logo: /assets/templogo.png

aux_links:
 FleetOptimiser OS2: https://github.com/OS2fleetoptimiser/OS2fleetoptimiser

plugins:
  - jekyll-relative-links
